---
title: "LTFHPlus"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{LTFHPlus}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In the examples, we will go over how the package ***LTFHPlus*** can be used to estimate a refined phenotype for the LT-FH++. More specifically, we will provide reproducible examples with explanations of the method and its code, such that users will be able to play around with the functions themselves. The code will be based on packages from the ***tidyverse***, if the read is not familiar with packages such as ***dplyr***, then a line-by-line understanding might not be possible, however the overall point should hopefully still be clear. 

## A word on the examples

The examples included here are meant to represent a simple application of the method, such that users are able to get a good idea of how to use the functions in the package and what to expect as output. The genetic liabilities are meant to be used as a phenotype for genome-wide association studies(GWAS). We recommend using software such as [PLINK](https://www.cog-genomics.org/plink/), [BOLT](https://alkesgroup.broadinstitute.org/BOLT-LMM/BOLT-LMM_manual.html), or R-based methods such as [bigsnpr](https://privefl.github.io/bigsnpr/) to perform the GWAS. 


The examples will follow this overarching structure:

* Packages used
* Global Settings
  + prevalence, number of individuals, heritability, etc...
* Setting up input
  + Assigning necessary information, e.g. family history.
  + subsections for each input needed with prints
* function call to estimate genetic liabilities


<!-- ```{r} -->
<!-- plot(seq(10,100), LTFHPlus::age_to_cir(age = seq(10,100))) -->
<!-- ``` -->
## What would you like to read about?


Here is an overview of what you can learn more about:


LT-FH++ method description & its applications

* format of input data
  + what does the prevalence information look like?
  + How do we input the thresholds and family history information?
* what do i do, if I do not have complete information on some individuals?
  + estimate genetic liability without family history, but with prevalence information
  + estimate genetic liability with family history, but without prevalence
  + estimate genetic liability with family history and prevalence information
  + correlated traits (still pending)


