# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtmvnorm_gibbs_cpp <- function(P, sd, lower, upper, fixed, to_return, x, n_sim, burn_in) {
    .Call('_LTFHPlus_rtmvnorm_gibbs_cpp', PACKAGE = 'LTFHPlus', P, sd, lower, upper, fixed, to_return, x, n_sim, burn_in)
}

