# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs Sampler for the truncated Normal distribution.
#'  
#' @param P conditional covariance matrix
#' @param sd  covariance matrix
#' @param lower lower limit
#' @param upper upper limit
#' @param fixed logical vector, which entries are fixed?
#' @param to_return Which entries to return
#' @param x #starting value
#' @param n_sim number of simulations to perform after the burn in period
#' @param burn_in burn in period
#' 
#' @export
rtmvnorm_gibbs_cpp <- function(P, sd, lower, upper, fixed, to_return, x, n_sim, burn_in) {
    .Call(`_LTFHPlus_rtmvnorm_gibbs_cpp`, P, sd, lower, upper, fixed, to_return, x, n_sim, burn_in)
}

